### ISSUE TITLE
Some directives should apply to the ID type 

### ISSUE THREAD

**Issue by paul-pop** [graphql-java/graphql-java-extended-validation#21]
First and foremost, thank you for this library, it's fantastic and I hope it gets the love it deserves 🙂 

I am currently seeing an issue when I try to add certain directives to `ID` fields:

```
Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'graphQLSchema' threw exception; nested exception is graphql.AssertException: The directive rule '@NotBlank' cannot be placed on elements of type 'ID'"
```

I think some directives like `@NotEmpty`, `@NotBlank` to start off would really help on ID fields. If you want to be extra safe we could even add `@Pattern`, `@Expression`, `@Size` and others later.

If I get the chance I will work on this and raise a PR but currently a bit swamped.

**Comment by setchy** [comment]
@paul-pop - I got some time this morning and added ID scalar support to `@Pattern`, `@NotEmpty`, `@NotBlank` and `@Size`.  `@Expression` already supports all types.

PR open #24

**Comment by setchy** [comment]
@bbakerman just wanted to confirm if we close this issue after we've released new versions of 14.x.x and 15.x.x
