### ISSUE TITLE
Ignore validation on optional arguments

### ISSUE THREAD

**Issue by aoudiamoncef** [graphql-java/graphql-java-extended-validation#29]
Hi @bbakerman, @andimarek,

```graphql
    findCitiesByCityCode(
        cityCode: String! @NotEmpty @NotBlank @Size(min : 5, max : 5)
        postCode: String @NotEmpty @NotBlank @Size(min : 5, max : 5) # always triggered even if the argument doesn't supplied.
		...
    ): CityPage
```
I think that adding a flag to directive in order to tell constraints runner to ignore optional validations if argument doesn't exist. 

I'll try to add the behavior a PR. Please don't hesitate to give me feedbacks. 

Thank you

**Comment by enriquedacostacambio** [comment]
i believe validation should be completely skipped for all rules, given that graphql has nullability checks embedded in the type system.

**Comment by aoudiamoncef** [comment]
@setchy, what do you think about this PR ?
