### ISSUE TITLE
Feature Request: Support for list elements

### ISSUE THREAD

**Issue by pelletier197** [graphql-java/graphql-java-extended-validation#31]
It would be great to have support of validation for list items. 

For instance with this query schema

```graphql
            type Query {
                cars(targets: [String!]! @NotBlank) : [Car]
            }
```

The `@NotBlank` could validate that every element of the list is not blank. This applies indeed for all the validations, except maybe for the `expression`, which could still be useful to use on a full list

**Comment by hantsy** [comment]
For a list, it should be `@NotEmpty` to check if there is an item in the collection.

**Comment by hantsy** [comment]
`@NotBlank` in bean validation is generally used to check if it is a empty string or a string only contained whitespace in the string.

**Comment by pelletier197** [comment]
Technically speaking,  javax supports both collections and strings. https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/NotEmpty.html. NotEnpty will allow whitespace characters, while NotBlank will ensure you have at least one non whitespace char. 

But the way you can validate a list or the elements of a list with javax is as follow:

```Java
// list not empty 
public @NotEmpty List<String> field;

// strings in the list not empty
public List<@NotEmpty String> field;
```

The equivalent syntax does not compile in GraphQL.

```graphql
// works 
field: [String] @NotEmpty

// does not work
field: [String.@NotEmpty ]
```

Thus making it impossible to validate that strings are not empty and that lists are not empty at the same time. Same issue occurs with `@Size`.

In the linked MR, I came up with `@ContainerNotEmpty` and `@ContainerNotBlank` to counter that issue. So far, I have got no news from the maintainers, but if you have a better idea to counter the issue, I'll be happy to change it.
