### ISSUE TITLE
The directive rule '@Size' cannot be placed on elements of type 'ID'

### ISSUE THREAD

**Issue by aoudiamoncef** [graphql-java/graphql-java-extended-validation#32]
Hello,

Current documentation: 

![image](https://user-images.githubusercontent.com/22281426/94785742-5dfee980-03d0-11eb-8db4-99e7a229a897.png)

When i tested:
```log
Caused by: graphql.AssertException: The directive rule '@Size' cannot be placed on elements of type 'ID'
```
Thanks

**Comment by bbakerman** [comment]
We just released a version with exactly this capability

**Comment by bbakerman** [comment]
See 15.0.2

**Comment by aoudiamoncef** [comment]
Hi @bbakerman,

`id: ID! @NotEmpty @NotBlank @Size(min : 24, max : 36)`.

Could we have the same behavior with @NotEmpty @NotBlank in next releases ? 

Thanks
