### ISSUE TITLE
Update rule suitability to schema build time  when graphql-java is fixed upstream

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java-extended-validation#36]
#17 and #30  moved the "suitability check" of a rule to DataFectehr runtime to work around a problem in SchemaDirectiveWiring when the true schema is not built at the time it is called back.

The workaround means that the DataFetcher is not as fast as it could be on 1st access.

We need to move back to early rule suitability checks at schema build time to ensure the most performant system.

This can only be done once graphql-java is fixed

See https://github.com/graphql-java/graphql-java/issues/2070

**Comment by setchy** [comment]
I noted this upstream change has now been completed. I'll see if I can spend some time on this later this week

**Comment by setchy** [comment]
I noticed the upstream bug graphql-java/graphql-java#2070 has been resolved in v16.x

**Comment by dondonz** [comment]
Closing this issue as https://github.com/graphql-java/graphql-java/issues/2070 has been fixed and the version in this repo has been updated.
