### ISSUE TITLE
RuntimeException in spring-boot-2.5.1 is necessary to force hibernate-validator downgrade

### ISSUE THREAD

**Issue by sbilello** [graphql-java/graphql-java-extended-validation#50]
If I use this version:

```
	implementation 'com.graphql-java:graphql-java-extended-validation:16.0.0'
```

I had to add to my `build.gradle`
```
configurations.all {
	resolutionStrategy {
		force 'org.hibernate.validator:hibernate-validator:6.1.6.Final'
	}
}
```
to avoid a `NoSuchMethodError` because `spring-boot-2.5.1` brings `hibernate-validator:6.2.0.Final`

```java.lang.NoSuchMethodError: 'void org.hibernate.validator.internal.engine.MessageInterpolatorContext.<init>```

**Comment by WtfJoke** [comment]
Had the same problem. I solved it by using (gradle kotlin dsl):
extra["hibernate-validator.version"] = "6.1.6.Final"
