### ISSUE TITLE
Issue with Micronaut framework with Kotlin Not able to use the annotations.

### ISSUE THREAD

**Issue by NiDargan** [graphql-java/graphql-java-extended-validation#93]
Do you have any documentation or example for this library to work with Micronaut framework with Kotlin. I want to use this library
in my project but i am unable to use the annotations is there any external library used to generate the annotations.

Project Framework Details -
Micronaut Framework - 3.7.4
Language - Kotlin 1.7.10
Build System - Gradle 7.6.1

// GraphQl library details -
  ```
  implementation("io.micronaut.graphql:micronaut-graphql")
    implementation("com.expediagroup:graphql-kotlin-schema-generator:6.0.6-GRAAL")
    implementation("com.expediagroup:graphql-kotlin-federation:6.0.6-GRAAL")
    implementation("com.graphql-java:graphql-java:21.0")

    implementation("com.graphql-java:graphql-java-extended-validation:21.0")
```

GraalVm for binary

**Comment by bbakerman** [comment]
Sorry we dont have doco or examples.  your effectively asking how to integrate with `kotlin-federation` and `micronaut-graphql` and we dont know.
