### ISSUE TITLE
v21 release with hibernate-validator-6.2.0.Final?

### ISSUE THREAD

**Issue by crankydillo** [graphql-java/graphql-java-extended-validation#94]
Is it possible to create a v21 release using hibernate-validator-6.2.0.Final?  We have some issues upgrading to the latest version of jakarta, but ultimately need to use v21 graphql-java and extended validation for some amount of time.  Maybe we could contribute a PR.

Thanks!

**Comment by dondonz** [comment]
Hello, I understand the pain of the Jakarta migration, having had to do the same at work recently.

Given we're a very small team of volunteers helping in our spare time, I do not wish to support multiple Hibernate releases. A key reason for supporting multiple Hibernate releases was to address compatibility problems with Spring Boot (of course, there were non-Spring related issues too). Now that Spring Boot 3 has been released for more than a year and Spring Boot 2.7 non-commercial support has ended, most folks have upgraded to Spring Boot 3 and the main reason for multiple Hibernate releases has been resolved. Original GitHub issue: https://github.com/graphql-java/graphql-java-extended-validation/issues/52

Sorry, I know the migration can be a real pain. I appreciate you offering a PR, however in this case it's more involved, it would be continuing to maintain two parallel versions of the project.
